public class HUDTestXML{

    //public Static String Test3rdXMLContent='';
    public Static String TestXMLContent = '<?xml version="1.0" encoding="utf-8"?>'+
                            '<HQInspection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://inspection.review.xsd">'+
                            '  <tbl_HQS_52580_Data>'+
                            '    <ID xmlns="">94</ID>'+
                            '    <Inspection_ID xmlns="">1228</Inspection_ID>'+
                            '    <Reviewer_ID xmlns="">37</Reviewer_ID>'+
                            '    <Reviewer_Name xmlns="">Shockley, Pierre</Reviewer_Name>'+
                            '    <Contractor xmlns="">CGI</Contractor>'+
                            '    <PHA_Inspector_Name xmlns="">DAmbrosio, Sam</PHA_Inspector_Name>'+
                            '    <PHA_Employee xmlns="">true</PHA_Employee>'+
                            '    <PHA_Code xmlns="">Cleveland</PHA_Code>'+
                            '    <Date_of_PHA_HQS_Inspection xmlns="">2012-04-13T00:00:00</Date_of_PHA_HQS_Inspection>'+
                            '    <Date_of_Contractor_Review xmlns="">2014-07-30T13:17:00</Date_of_Contractor_Review>'+
                            '    <Type_of_Inspection xmlns="">Initial</Type_of_Inspection>'+
                            '    <HQS_Review_Type xmlns="">3</HQS_Review_Type>'+
                            '    <Unit_Street_Address xmlns="">14015 Superior Rd. # 401</Unit_Street_Address>'+
                            '    <Unit_City xmlns="">East Cleveland</Unit_City>'+
                            '    <Unit_County xmlns="">Cuyahoga</Unit_County>'+
                            '    <Unit_State xmlns="">OH</Unit_State>'+
                            '    <Unit_Zip xmlns="">44118     </Unit_Zip>'+
                            '    <Name_of_Family xmlns="">Tia Taylor</Name_of_Family>'+
                            '    <Current_Street_Address xmlns="">14015 Superior Rd. # 401</Current_Street_Address>'+
                            '    <Current_City xmlns="">East Cleveland</Current_City>'+
                            '    <Current_County xmlns="">Cuyahoga</Current_County>'+
                            '    <Current_State xmlns="">OH</Current_State>'+  
                            '    <Current_Zip xmlns="">44118     </Current_Zip>'+
                            '    <Unit_Current_Telephone_Number_of_Family xmlns="">(216)203-3310</Unit_Current_Telephone_Number_of_Family>'+
                            '    <Housing_Type xmlns="">Hi Rise 5 or More Stories</Housing_Type>'+
                            '    <Number_of_Children_in_Family_Under_6 xmlns="">1</Number_of_Children_in_Family_Under_6>'+
                            '    <Name_of_Owner_or_Agent_Authorized_to_Lease_Unit_Inspected xmlns="">Marengo Heights LLC</Name_of_Owner_or_Agent_Authorized_to_Lease_Unit_Inspected>'+
                            '    <Telephone_of_Owner_or_Agent xmlns="">(216)932-4407</Telephone_of_Owner_or_Agent>'+
                            '    <Address_of_Owner_or_Agent xmlns="">13995 Superior Rd. East Cleveland OH 44118</Address_of_Owner_or_Agent>'+
                            '    <Summary_Decision_on_the_Unit xmlns="">Fail</Summary_Decision_on_the_Unit>'+
                            '    <Unit_Size xmlns="">3</Unit_Size>'+
                            '    <Year_Constructed xmlns="">1949</Year_Constructed>'+
                            '    <Number_of_Sleeping_Rooms xmlns="">0</Number_of_Sleeping_Rooms>'+
                            '    <Unit_Start_Time xmlns="">2014-07-31T03:57:54</Unit_Start_Time>'+
                            '    <Unit_End_Time xmlns="">2014-07-31T04:18:44</Unit_End_Time>'+
                            '    <PHA_HQS_Result xmlns="">Fail</PHA_HQS_Result>'+
                            '    <Contractor_QC_Present xmlns="">true</Contractor_QC_Present>'+
                            '    <Contractor_QC_Name xmlns="">Pierre Shockley</Contractor_QC_Name>'+
                            '    <REAC_QA_Present xmlns="">true</REAC_QA_Present>'+
                            '    <REAC_QA_Name xmlns="">Pierre Shockley</REAC_QA_Name>'+
                            '    <General_Photo xmlns="">iVBORw0KGgoAAAANSUhEUgAAAPAAAAFACAIAAAANimYEAAAAA3NCSVQICAjb4U/gAAAgAElEQVR4nJy7Wa9lWXIe9n0Ra+19pnvumDezMrPGrqruNimSIgmaoy1IFmnYkEAIBmjAfrPf/eh1pJTztn3zxkmWqMsHJCTNqHU0YN+Cb1SHH01lMGdhktBAr9ydaxA9FocoME3WV4v27qEQ7k/9iOXBkSIabPkVsgnzpKYskQIAiKm0S6zp6bjHWUrVpgAExIkvJn+ohF3pEvSQ5PQvw6/LlAZSBnSNb6ZoJJmWM2F7bsleLu+lbIWOuimTJd21vf3IrdK+Lx/jtjX7S/gl79/fuQutF3f8GG5VP+2J0SBwF2vPt3TGHQyXQUfBxhF/H+PsbwZxGUUjgAAAABJRU5ErkJggg==</General_Photo>'+
                            '    <tbl_HQS_Item_Details>'+
                            '      <Item_ID xmlns="">19504</Item_ID>'+
                            '      <Inspection_ID xmlns="">1228</Inspection_ID>'+
                            '      <HQS_Section_Number xmlns="">1</HQS_Section_Number>'+
                            '      <HQS_Section_Title xmlns="">Living Room</HQS_Section_Title>'+
                            '      <HQS_line_Item_Number xmlns="">1</HQS_line_Item_Number>'+
                            '      <HQS_Deficiency_Category xmlns="">Living Room Present</HQS_Deficiency_Category>'+
                            '      <Contractor_HQS_Decision xmlns="">Pass</Contractor_HQS_Decision>'+
                            '      <LT_Deficiency xmlns="">SampleLT_Deficiency</LT_Deficiency>'+
                            '      <LQA_Category xmlns="">SampleLQA_Category</LQA_Category>'+
                            '      <Local_PHA_Decision xmlns="">SampleLocal_PHA_Decision</Local_PHA_Decision>'+
                            '      <Local_PHA_Details xmlns="">SampleLocal_PHA_Details</Local_PHA_Details>'+
                            '      <Deficiency_Location xmlns="">SampleDeficiency_Location</Deficiency_Location>'+
                            '      <Deficiency_Comments xmlns="">SampleDeficiency_Comments</Deficiency_Comments>'+
                            '      <HQS_Category_ID xmlns="">1234</HQS_Category_ID>'+
                            '      <PHA_Decision xmlns="">Pass</PHA_Decision>'+
                            '      <Time_of_Deficiency xmlns="">0001-01-01T00:00:00</Time_of_Deficiency>'+
                            '    </tbl_HQS_Item_Details>'+
                            '    <tbl_HQS_Item_Details>'+
                            '      <Item_ID xmlns="">17229</Item_ID>'+
                            '      <Inspection_ID xmlns="">1198</Inspection_ID>'+
                            '      <HQS_Section_Number xmlns="">4</HQS_Section_Number>'+
                            '      <HQS_Section_Title xmlns="">Other Rooms Used for Living and Halls</HQS_Section_Title>'+
                            '      <HQS_line_Item_Number xmlns="">7</HQS_line_Item_Number>'+
                            '      <HQS_Deficiency_Category xmlns="">Wall Condition</HQS_Deficiency_Category>'+
                            '      <Contractor_HQS_Decision xmlns="">Fail</Contractor_HQS_Decision>'+
                            '      <Contractor_HQS_Details xmlns="">Not fixed</Contractor_HQS_Details>'+
                            '      <PHA_Decision xmlns="">Fail</PHA_Decision>'+
                            '      <PHA_Details xmlns="">Burglary bars must have emergency break always (Image on File)</PHA_Details>'+
                            '      <Room_Location_1 xmlns="">Right</Room_Location_1>'+
                            '      <Room_Location_2 xmlns="">Front</Room_Location_2>'+
                            '      <Floor_Level xmlns="">1</Floor_Level>'+
                            '      <Room_Code xmlns="">1</Room_Code>'+
                            '      <Other_Room_Code_Description xmlns="">Bedroom rf</Other_Room_Code_Description>'+
                            '      <Photo xmlns="">'+
                            '        <FileData>iVBORw0KGgoAAAANSUtl53R7utsc3p7fvT+eFMSmP7aDGwBqmwW4KjwprqNBrd3kHU1xQJh3hRPTMOag/Abu0OcO4a9LLlrVwTFfoAgni2iqrnP1yG15euRONgSGXA9b3TKugd/kaquMqcsCtevjpqes+xJ09tlvHjz///Pf/9Pnp+Uv2dGuLebqaP7xZGyOfrvvn574/f3455LK2xV988/bu8f6bx5M33m+nYDHG+LiPj//hD3/36YO1myIg79q37JnSuhR7O9DL9lmZLcXamrmCZpAmTbxxqoDMJx/fphfWEilMW4JFjWFr5L//5b+/9zX/ScWXzBOJ2mU+NOT1NYsTxef3sOMZ3BPPK8/gyrareCSAiwMB39Jb0J40nRIepFrJKSgk0TK7pEgyfZOphIOlIBsMCmhwgDga71jRnTJAQTXgJhS5abgwlImcNZaIlaVmE2TJaDJsjffBYDzd/uLS74KIuzl54/Y2fjuNOwrjVXgKnqgGnxk5Prf5PqSa21ugzKZ7ObbPwRzwX/F+dj5qMnFNvvQAAAABJRU5ErkJggg==</FileData>'+
                            '        <FileName>P2014-07-25 15-24_59180.jpg</FileName>'+
                            '        <FileTimeStamp>2014-07-25T15:24:46</FileTimeStamp>'+
                            '        <FileType>jpg</FileType>'+
                            '      </Photo>'+
                            '      <Time_of_Deficiency xmlns="">2014-07-25T15:24:46</Time_of_Deficiency>'+
                            '      <tbl_comparison_explaination_photo>'+
                            '        <Comparison_Result xmlns="">Confirmed</Comparison_Result>'+
                            '        <Time_stamp xmlns="">2014-07-25T15:24:46</Time_stamp>'+
                            '      </tbl_comparison_explaination_photo>'+
                            '    </tbl_HQS_Item_Details>'+
                            '    '+
                            '    <tbl_PHA_Pdf>'+
                            '      <mimetype xmlns="">application/pdf</mimetype>'+
                            '      <filename xmlns="">41562.pdf</filename>'+
                            '      <content xmlns="">JVBERi0xLgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnBkZj0iaHR0cDovL25zLmFkb2JlLmNvbS9wZGYvMS4zLyIKICAgICAgICAgICAgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iPgogICAgICAgICA8ZGM6Zm9ybWF0PmFwcGxpY2F0aW9uL3BkZjwvZGM6Zm9ybWF0PgogICAgICAgICA8ZGM6Y3JlYXRvcj4KICAgICAgICAgICAgPHJkZjpTZXE+CiAgICAgICAgICAgICAgIDxyZGY6bGkvPgogICAgICAgICAgICA8L3JkZjpTZXE+CiAgICAgICAgIDwvZGM6Y3JlYXRvcj4KICAgICAgICAgPGRjOmRlc2NyaXB0aW9uPgogICAgICAgICAgICA8cmRmOkFsdD4KICAgICAgICAgICAgICAgPHJkZjpsaSB4bWw6bGFuZz0ieC1kZWZhdWx0Ii8+CiAgICAIDIgMV0+PnN0cmVhbQ0KaN5iYgACJkapcAYmBsaLQIL7C5BgALPuwsS4fGAs/iCQ7CUgIaoNYj0CyZ4BEuLGINkkkLrTIOIv0NDcvyAlDIwwgvEfQIABAAD6Dj8NCmVuZHN0cmVhbQ1lbmRvYmoNc3RhcnR4cmVmDQoxMTYNCiUlRU9GDQo=</content>'+
                            '    </tbl_PHA_Pdf>'+
                            '  </tbl_HQS_52580_Data>'+
                            '</HQInspection>';
        public Static String TestErrorXMLContent = '<?xml version="1.0" encoding="utf-8"?>'+
                            '<HQInspection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://inspection.review.xsd">'+
                            '  <tbl_HQS_52580_Data>'+
                            '    <ID xmlns="">94</ID>'+
                            '    <Inspection_ID xmlns="">1228</Inspection_ID>'+
                            '    <Reviewer_ID xmlns="">37</Reviewer_ID>'+
                            '    <Reviewer_Name xmlns="">Shockley, Pierre</Reviewer_Name>'+
                            '    <Contractor xmlns="">CGI</Contractor>'+
                            '    <PHA_Inspector_Name xmlns="">DAmbrosio, Sam</PHA_Inspector_Name>'+
                            '    <PHA_Employee xmlns="">true</PHA_Employee>'+
                            '    <PHA_Code xmlns="">Cleveland</PHA_Code>'+
                            '    <Date_of_PHA_HQS_Inspection xmlns="">2012-04-13T00:00:00</Date_of_PHA_HQS_Inspection>'+
                            '    <Date_of_Contractor_Review xmlns="">2014-07-30T13:17:00</Date_of_Contractor_Review>'+
                            '    <Type_of_Inspection xmlns="">Initial</Type_of_Inspection>'+
                            '    <HQS_Review_Type xmlns="">3</HQS_Review_Type>'+
                            '    <Unit_Street_Address xmlns="">14015 Superior Rd. # 401</Unit_Street_Address>'+
                            '    <Unit_City xmlns="">East Cleveland</Unit_City>'+
                            '    <Unit_County xmlns="">Cuyahoga</Unit_County>'+
                            '    <Unit_State xmlns="">OH</Unit_State>'+
                            '    <Unit_Zip xmlns="">44118     </Unit_Zip>'+
                            '    <Name_of_Family xmlns="">Tia Taylor</Name_of_Family>'+
                            '    <Current_Street_Address xmlns="">14015 Superior Rd. # 401</Current_Street_Address>'+
                            '    <Current_City xmlns="">East Cleveland</Current_City>'+
                            '    <Current_County xmlns="">Cuyahoga</Current_County>'+
                            '    <Current_State xmlns="">OH</Current_State>'+  
                            '    <Current_Zip xmlns="">44118     </Current_Zip>'+
                            '    <Unit_Current_Telephone_Number_of_Family xmlns="">(216)203-3310</Unit_Current_Telephone_Number_of_Family>'+
                            '    <Housing_Type xmlns="">Other</Housing_Type>'+
                            '    <Number_of_Children_in_Family_Under_6 xmlns="">1</Number_of_Children_in_Family_Under_6>'+
                            '    <Name_of_Owner_or_Agent_Authorized_to_Lease_Unit_Inspected xmlns="">Marengo Heights LLC</Name_of_Owner_or_Agent_Authorized_to_Lease_Unit_Inspected>'+
                            '    <Telephone_of_Owner_or_Agent xmlns="">(216)932-4407</Telephone_of_Owner_or_Agent>'+
                            '    <Address_of_Owner_or_Agent xmlns="">13995 Superior Rd. East Cleveland OH 44118</Address_of_Owner_or_Agent>'+
                            '    <Summary_Decision_on_the_Unit xmlns="">Pass</Summary_Decision_on_the_Unit>'+
                            '    <Unit_Size xmlns="">3</Unit_Size>'+
                            '    <Year_Constructed xmlns="">1949</Year_Constructed>'+
                            '    <Number_of_Sleeping_Rooms xmlns="">0</Number_of_Sleeping_Rooms>'+
                            '    <Unit_Start_Time xmlns="">2014-07-31T03:57:54</Unit_Start_Time>'+
                            '    <Unit_End_Time xmlns="">2014-07-31T04:18:44</Unit_End_Time>'+
                            '    <PHA_HQS_Result xmlns="">Fail</PHA_HQS_Result>'+
                            '    <Contractor_QC_Present xmlns="">true</Contractor_QC_Present>'+
                            '    <REAC_QA_Present xmlns="">true</REAC_QA_Present>'+
                            '    <General_Photo xmlns="">iVBORw0KGgoAAAANSUhEUgAAAPAAAAFACAIAAAANimYEAAAAA3NCSVQICAjb4U/gAAAgAElEQVR4nJy7Wa9lWXIe9n0Ra+19pnvumDezMrPGrqruNimSIgmaoy1IFmnYkEAIBmjAfrPf/eh1pJTztn3zxkmWqMsHJCTNqHU0YN+Cb1SHH01lMGdhktBAr9ydaxA9FocoME3WV4v27qEQ7k/9iOXBkSIabPkVsgnzpKYskQIAiKm0S6zp6bjHWUrVpgAExIkvJn+ohF3pEvSQ5PQvw6/LlAZSBnSNb6ZoJJmWM2F7bsleLu+lbIWOuimTJd21vf3IrdK+Lx/jtjX7S/gl79/fuQutF3f8GG5VP+2J0SBwF2vPt3TGHQyXQUfBxhF/H+PsbwZxGUUjgAAAABJRU5ErkJggg==</General_Photo>'+
                            '    <tbl_HQS_Item_Details>'+
                            '      <Item_ID xmlns="">19504</Item_ID>'+
                            '      <Inspection_ID xmlns="">1228</Inspection_ID>'+
                            '      <HQS_Section_Number xmlns="">1</HQS_Section_Number>'+
                            '      <HQS_Section_Title xmlns="">Living Room</HQS_Section_Title>'+
                            '      <HQS_line_Item_Number xmlns="">1</HQS_line_Item_Number>'+
                            '      <HQS_Deficiency_Category xmlns="">Living Room Present</HQS_Deficiency_Category>'+
                            '      <Contractor_HQS_Decision xmlns="">Pass</Contractor_HQS_Decision>'+
                            '      <LT_Deficiency xmlns="">SampleLT_Deficiency</LT_Deficiency>'+
                            '      <LQA_Category xmlns="">SampleLQA_Category</LQA_Category>'+
                            '      <Local_PHA_Decision xmlns="">SampleLocal_PHA_Decision</Local_PHA_Decision>'+
                            '      <Local_PHA_Details xmlns="">SampleLocal_PHA_Details</Local_PHA_Details>'+
                            '      <Deficiency_Location xmlns="">SampleDeficiency_Location</Deficiency_Location>'+
                            '      <Deficiency_Comments xmlns="">SampleDeficiency_Comments</Deficiency_Comments>'+
                            '      <HQS_Category_ID xmlns="">1234</HQS_Category_ID>'+
                            '      <PHA_Decision xmlns="">Fail</PHA_Decision>'+
                            '      <Time_of_Deficiency xmlns="">0001-01-01T00:00:00</Time_of_Deficiency>'+
                            '    </tbl_HQS_Item_Details>'+
                            '    <tbl_HQS_Item_Details>'+
                            '      <Item_ID xmlns="">17229</Item_ID>'+
                            '      <Inspection_ID xmlns="">1198</Inspection_ID>'+
                            '      <HQS_Section_Number xmlns="">4</HQS_Section_Number>'+
                            '      <HQS_Section_Title xmlns="">Other Rooms Used for Living and Halls</HQS_Section_Title>'+
                            '      <HQS_line_Item_Number xmlns="">7</HQS_line_Item_Number>'+
                            '      <HQS_Deficiency_Category xmlns="">Wall Condition</HQS_Deficiency_Category>'+
                            '      <Contractor_HQS_Decision xmlns="">Fail</Contractor_HQS_Decision>'+
                            '      <Contractor_HQS_Details xmlns="">Not fixed</Contractor_HQS_Details>'+
                            '      <PHA_Decision xmlns="">Pass</PHA_Decision>'+                           
                            '      <Photo xmlns="">'+
                            '        <FileData>iVBORw0KGgoAAAANSUtl53R7utsc3p7fvT+eFMSmP7aDGwBqmwW4KjwprqNBrd3kHU1xQJh3hRPTMOag/Abu0OcO4a9LLlrVwTFfoAgni2iqrnP1yG15euRONgSGXA9b3TKugd/kaquMqcsCtevjpqes+xJ09tlvHjz///Pf/9Pnp+Uv2dGuLebqaP7xZGyOfrvvn574/f3455LK2xV988/bu8f6bx5M33m+nYDHG+LiPj//hD3/36YO1myIg79q37JnSuhR7O9DL9lmZLcXamrmCZpAmTbxxqoDMJx/fphfWEilMW4JFjWFr5L//5b+/9zX/ScWXzBOJ2mU+NOT1NYsTxef3sOMZ3BPPK8/gyrareCSAiwMB39Jb0J40nRIepFrJKSgk0TK7pEgyfZOphIOlIBsMCmhwgDga71jRnTJAQTXgJhS5abgwlImcNZaIlaVmE2TJaDJsjffBYDzd/uLS74KIuzl54/Y2fjuNOwrjVXgKnqgGnxk5Prf5PqSa21ugzKZ7ObbPwRzwX/F+dj5qMnFNvvQAAAABJRU5ErkJggg==</FileData>'+
                            '        <FileName>P2014-07-25 15-24_59180.jpg</FileName>'+
                            '        <FileTimeStamp>2014-07-25T15:24:46</FileTimeStamp>'+
                            '        <FileType>jpg</FileType>'+
                            '      </Photo>'+
                            '      <Time_of_Deficiency xmlns="">2014-07-25T15:24:46</Time_of_Deficiency>'+
                            '      <tbl_comparison_explaination_photo>'+
                            '        <Comparison_Result xmlns="">Same</Comparison_Result>'+
                            '        <Time_stamp xmlns="">2014-07-25T15:24:46</Time_stamp>'+
                            '      </tbl_comparison_explaination_photo>'+
                            '    </tbl_HQS_Item_Details>'+
                            '    '+
                            '    <tbl_PHA_Pdf>'+
                            '      <mimetype xmlns="">application/pdf</mimetype>'+
                            '      <filename xmlns="">41562.pdf</filename>'+
                            '      <content xmlns="">JVBERi0xLgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnBkZj0iaHR0cDovL25zLmFkb2JlLmNvbS9wZGYvMS4zLyIKICAgICAgICAgICAgeG1sbnM6eG1wTU09Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iPgogICAgICAgICA8ZGM6Zm9ybWF0PmFwcGxpY2F0aW9uL3BkZjwvZGM6Zm9ybWF0PgogICAgICAgICA8ZGM6Y3JlYXRvcj4KICAgICAgICAgICAgPHJkZjpTZXE+CiAgICAgICAgICAgICAgIDxyZGY6bGkvPgogICAgICAgICAgICA8L3JkZjpTZXE+CiAgICAgICAgIDwvZGM6Y3JlYXRvcj4KICAgICAgICAgPGRjOmRlc2NyaXB0aW9uPgogICAgICAgICAgICA8cmRmOkFsdD4KICAgICAgICAgICAgICAgPHJkZjpsaSB4bWw6bGFuZz0ieC1kZWZhdWx0Ii8+CiAgICAIDIgMV0+PnN0cmVhbQ0KaN5iYgACJkapcAYmBsaLQIL7C5BgALPuwsS4fGAs/iCQ7CUgIaoNYj0CyZ4BEuLGINkkkLrTIOIv0NDcvyAlDIwwgvEfQIABAAD6Dj8NCmVuZHN0cmVhbQ1lbmRvYmoNc3RhcnR4cmVmDQoxMTYNCiUlRU9GDQo=</content>'+
                            '    </tbl_PHA_Pdf>'+
                            '  </tbl_HQS_52580_Data>'+
                            '</HQInspection>';
}